import type { MeetingTask, TaskStatus } from "@/lib/mockTasks";

// Latest end-of-meeting action items, generated by the ctl-side Talon subagent and
// POSTed here, plus single-item add/remove edits driven by voice commands. Lives in
// process memory alongside the transcript buffer (transcriptHub.ts).
let tasks: MeetingTask[] = [];

// Monotonic id source so add/remove never reuses an id even as the list shifts.
let idCounter = 0;
function makeId(): string {
  idCounter += 1;
  return `t_${idCounter.toString().padStart(3, "0")}`;
}

interface ActionItemInput {
  title: string;
  assignee?: string;
  status?: TaskStatus;
}

function coerceStatus(value: unknown): TaskStatus {
  return value === "done" ? "done" : "open";
}

function normalizeInput(item: ActionItemInput): MeetingTask | undefined {
  const title = typeof item.title === "string" ? item.title.trim() : "";
  if (!title) return undefined;
  return {
    id: makeId(),
    title,
    assignee:
      typeof item.assignee === "string" && item.assignee.trim()
        ? item.assignee.trim()
        : "Unassigned",
    status: coerceStatus(item.status),
  } satisfies MeetingTask;
}

/** Replaces the whole list (end-of-meeting generation). */
export function setTasks(items: ActionItemInput[]): MeetingTask[] {
  tasks = items
    .map(normalizeInput)
    .filter((task): task is MeetingTask => task !== undefined);
  return tasks;
}

/** Appends a single action item (voice "add" command). */
export function addTask(item: ActionItemInput): MeetingTask | undefined {
  const task = normalizeInput(item);
  if (!task) return undefined;
  tasks = [...tasks, task];
  return task;
}

/** Removes an action item by its exact id (used after the delegate resolves a match). */
export function removeTaskById(id: string): MeetingTask | undefined {
  const target = id.trim();
  if (!target) return undefined;
  const index = tasks.findIndex(task => task.id === target);
  if (index === -1) return undefined;
  const [removed] = tasks.splice(index, 1);
  return removed;
}

/**
 * Removes the action item that best matches `query` (lexical fallback). Spoken
 * commands reference items by description, so match leniently: exact title first,
 * then a substring either direction. Returns the removed task, if any.
 */
export function removeTask(query: string): MeetingTask | undefined {
  const needle = query.trim().toLowerCase();
  if (!needle) return undefined;

  let index = tasks.findIndex(task => task.title.toLowerCase() === needle);
  if (index === -1) {
    index = tasks.findIndex(task => task.title.toLowerCase().includes(needle));
  }
  if (index === -1) {
    index = tasks.findIndex(task => needle.includes(task.title.toLowerCase()));
  }
  if (index === -1) return undefined;

  const [removed] = tasks.splice(index, 1);
  return removed;
}

export function getTasks(): MeetingTask[] {
  return tasks;
}
