import type { MeetingTask, TaskStatus } from "@/lib/mockTasks";

// Latest end-of-meeting action items, generated by the ctl-side Talon subagent and
// POSTed here. Replace-on-write: each generation overwrites the previous list. Lives
// in process memory alongside the transcript buffer (transcriptHub.ts).
let tasks: MeetingTask[] = [];

interface ActionItemInput {
  title: string;
  assignee?: string;
  status?: TaskStatus;
}

function coerceStatus(value: unknown): TaskStatus {
  return value === "done" ? "done" : "open";
}

/** Replaces the stored action items, assigning stable ids and defaulting status. */
export function setTasks(items: ActionItemInput[]): MeetingTask[] {
  tasks = items
    .map((item, index) => {
      const title = typeof item.title === "string" ? item.title.trim() : "";
      if (!title) return undefined;
      return {
        id: `t_${(index + 1).toString().padStart(3, "0")}`,
        title,
        assignee:
          typeof item.assignee === "string" && item.assignee.trim()
            ? item.assignee.trim()
            : "Unassigned",
        status: coerceStatus(item.status),
      } satisfies MeetingTask;
    })
    .filter((task): task is MeetingTask => task !== undefined);
  return tasks;
}

export function getTasks(): MeetingTask[] {
  return tasks;
}
